"""Editorial curriculum mapping for the 2020 VCE Physics exam against the
official VCE Physics Study Design 2017-2023 (data/curriculum/study-design-
2016.json). Every mapping below was made by reading each question's actual
text (extracted directly from previous-design-2017-2023/2020-physics-
exam.pdf) against the study design's own key knowledge dot points. This is
deliberately a plain Python literal (not hand-typed JSON) so interactionId
typos fail loudly (KeyError) rather than silently producing an unmapped
question. See scripts/build_2023_curriculum_map.py for the sibling script
this mirrors.

Output: data/curriculum/2020-mapping.json
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "data" / "curriculum" / "2020-mapping.json"

# (interactionId, unit, areaOfStudy, topic, skills, confidence)
MAPPING = [
    # ---- Section A ----
    ("A1", "Unit 3", "U3AoS1", "Charge signs from an electric field line diagram of equal charges", ["field shapes and directions, attractive/repulsive effects, dipoles and monopoles"], "high"),
    ("A2", "Unit 3", "U3AoS1", "Surface gravity of a moon from its mass and radius", ["gravitational field and gravitational force concepts"], "high"),
    ("A3", "Unit 3", "U3AoS1", "Speed of a charged particle exiting a magnetic field", ["magnetic force on a charged particle: F = qvB"], "high"),
    ("A4", "Unit 3", "U3AoS1", "Effect of a speed change on the radius of a particle's circular path", ["radius of the path followed by a low-velocity electron in a magnetic field"], "high"),
    ("A5", "Unit 3", "U3AoS2", "Magnetic flux through a coil perpendicular to a field", ["magnetic flux: Phi = B*A"], "high"),
    ("A6", "Unit 3", "U3AoS2", "Average induced EMF as a loop enters a magnetic field", ["generation of emf ... rate of change of magnetic flux"], "high"),
    ("A7", "Unit 3", "U3AoS2", "Output of an ideal transformer given a constant DC input", ["ideal transformer action"], "high"),
    ("A8", "Unit 3", "U3AoS3", "Forces on a ball at the bottom of a vertical circular path", ["Newton's second law to circular motion in a vertical plane"], "high"),
    ("A9", "Unit 3", "U3AoS3", "Net force comparison for two blocks pushed together", ["Newton's three laws of motion"], "high"),
    ("A10", "Unit 3", "U3AoS3", "Work done by a constant force over a distance", ["work done = constant force x distance moved"], "high"),
    ("A11", "Unit 3", "U3AoS3", "Momentum and kinetic energy of a satellite in a stable circular orbit", ["model natural and artificial satellite motion as uniform circular motion"], "high"),
    ("A12", "Unit 3", "U3AoS3", "Lorentz factor for a fast-moving proton", ["model mathematically time dilation and length contraction"], "high"),
    ("A13", "Unit 3", "U3AoS3", "Power generated by a star's mass-to-energy fusion rate", ["interpret Einstein's prediction ... mass-energy equivalence"], "high"),
    ("A14", "Unit 4", "U4AoS1", "Greatest diffraction effect from gap size and wavelength combinations", ["investigate and explain ... diffraction as the directional spread of various frequencies"], "high"),
    ("A15", "Unit 4", "U4AoS2", "Which statements about light-wave energy are correct", ["interpret spectra and calculate the energy of absorbed or emitted photons: delta E = hf"], "medium"),
    ("A16", "Unit 4", "U4AoS2", "Ranking metals by work function from an Ek-max-vs-frequency plot", ["kinetic energy of emitted photoelectrons: Ek max = hf - phi"], "high"),
    ("A17", "Unit 4", "U4AoS2", "Identifying the highest-energy transition on an energy-level diagram", ["analyse the absorption of photons by atoms ... frequency and wavelength of emitted photons"], "high"),
    ("A18", "Unit 4", "U4AoS2", "Best explanation for quantised atomic energy levels", ["describe the quantised states of the atom with reference to electrons forming standing waves"], "high"),
    ("A19", "Unit 4", "U4AoS3", "Best description of a scientific hypothesis", ["the nature of evidence that supports or refutes a hypothesis, model or theory"], "high"),
    ("A20", "Unit 4", "U4AoS2", "Graph shape for maximum photoelectron kinetic energy vs photon wavelength", ["kinetic energy of emitted photoelectrons: Ek max = hf - phi"], "high"),

    # ---- Section B ----
    ("B1", "Unit 3", "U3AoS1", "Sketching magnetic field lines between two nearby bar magnets", ["field shapes and directions, attractive/repulsive effects, dipoles and monopoles"], "high"),
    ("B2", "Unit 3", "U3AoS1", "Classifying gravitation, magnetism and electricity by monopoles/dipoles", ["field shapes and directions, attractive/repulsive effects, dipoles and monopoles"], "high"),
    ("B3a", "Unit 3", "U3AoS1", "Deriving the velocity-selector condition v0 = E/B", ["electric field acceleration of a charge: F = qE", "magnetic force on a charged particle: F = qvB"], "high"),
    ("B3b", "Unit 3", "U3AoS1", "Velocity of an electron passing straight through a velocity selector", ["electric field acceleration of a charge: F = qE", "magnetic force on a charged particle: F = qvB"], "high"),
    ("B3ci", "Unit 3", "U3AoS1", "Which aperture point faster-than-selected electrons reach", ["magnetic force on a charged particle: F = qvB"], "high"),
    ("B3cii", "Unit 3", "U3AoS1", "Explaining why faster electrons deflect further in a velocity selector", ["magnetic force on a charged particle: F = qvB"], "high"),
    ("B4a", "Unit 3", "U3AoS1", "Orbital radius of a satellite from its altitude", ["satellite motion modelled as uniform circular motion"], "high"),
    ("B4b", "Unit 3", "U3AoS1", "Orbital period of a satellite from its orbital radius", ["satellite motion modelled as uniform circular motion"], "high"),
    ("B4c", "Unit 3", "U3AoS1", "How a satellite maintains orbit without propulsion", ["force due to gravity and normal reaction force ... satellites in orbit"], "high"),
    ("B4d", "Unit 3", "U3AoS1", "Change in gravitational potential energy from a non-uniform field-altitude graph", ["the change in gravitational potential energy from area under a force-distance graph and area under a field-distance graph multiplied by mass"], "high"),
    ("B5a", "Unit 3", "U3AoS2", "Direction of induced current in a rotating DC-generator loop", ["explain the production of DC voltage in DC generators ... split ring commutators"], "high"),
    ("B5b", "Unit 3", "U3AoS2", "Average EMF over a quarter turn of a rotating loop", ["generation of emf ... rate of change of magnetic flux"], "high"),
    ("B5c", "Unit 3", "U3AoS2", "Sketching a DC generator's output EMF vs time", ["explain the production of DC voltage in DC generators"], "high"),
    ("B5d", "Unit 3", "U3AoS2", "Modifications that would increase a DC generator's output EMF", ["generation of emf ... rate of change of magnetic flux", "number of loops"], "high"),
    ("B6a", "Unit 3", "U3AoS2", "Whether flux increases, decreases or stays the same as a coil's shape changes", ["magnetic flux: Phi = B*A"], "high"),
    ("B6b", "Unit 3", "U3AoS2", "Explaining and finding the direction of an induced current from changing flux", ["generation of emf ... direction of induced emf in a coil"], "high"),
    ("B6c", "Unit 3", "U3AoS2", "Direction of induced currents through further shape changes", ["generation of emf ... direction of induced emf in a coil"], "high"),
    ("B7a", "Unit 3", "U3AoS2", "Peak voltage in a transformer's secondary coil from its RMS voltage", ["convert between rms, peak and peak-to-peak values of voltage and current"], "high"),
    ("B7b", "Unit 3", "U3AoS2", "Turns ratio of a step-down transformer", ["ideal transformer action"], "high"),
    ("B7c", "Unit 3", "U3AoS2", "RMS current in a transformer's primary coil", ["ideal transformer action"], "high"),
    ("B8a", "Unit 3", "U3AoS3", "Labelled forces on a ball moving in a horizontal circular path", ["uniform circular motion of an object moving in a horizontal plane: an object on the end of a string"], "high"),
    ("B8b", "Unit 3", "U3AoS3", "Speed of a ball in horizontal circular motion on a string", ["uniform circular motion of an object moving in a horizontal plane"], "high"),
    ("B9a", "Unit 3", "U3AoS3", "Initial velocity of a ball launched by a compressed spring", ["strain potential energy: ideal springs obeying Hooke's Law"], "high"),
    ("B9b", "Unit 3", "U3AoS3", "Speed of a ball after falling a vertical distance", ["conservation of energy and momentum in isolated systems"], "high"),
    ("B10a", "Unit 3", "U3AoS3", "Speed and direction of a car after a collision (momentum conservation)", ["conservation of energy and momentum in isolated systems"], "high"),
    ("B10b", "Unit 3", "U3AoS3", "Whether a vehicle collision is elastic or inelastic", ["elastic and inelastic collisions with reference to conservation of kinetic energy"], "high"),
    ("B10ci", "Unit 3", "U3AoS3", "Average force on a van from an impulsive collision", ["impulse in an isolated system: F*delta t = m*delta v"], "high"),
    ("B10cii", "Unit 3", "U3AoS3", "Average force on a car from the same collision (Newton's third law)", ["impulse in an isolated system: F*delta t = m*delta v", "Newton's three laws of motion"], "high"),
    ("B11a", "Unit 3", "U3AoS3", "Trip duration measured by a relativistic traveller's own clock", ["model mathematically time dilation ... t = t0*gamma"], "high"),
    ("B11b", "Unit 3", "U3AoS3", "Whether a travelling clock's measured time is a proper time", ["describe proper time (t0) as the time interval between two events ... at the same point in space"], "high"),
    ("B12a", "Unit 4", "U4AoS1", "Explaining how a bright interference fringe is formed", ["constructive and destructive interference from two sources with reference to coherent waves and path difference"], "high"),
    ("B12b", "Unit 4", "U4AoS1", "Wavelength of laser light from Young's double-slit fringe spacing", ["effect of wavelength, distance of screen and slit separation on interference patterns"], "high"),
    ("B13a", "Unit 4", "U4AoS1", "Wave speed on a guitar string from its standing-wave frequency", ["wave speed, frequency, wavelength and period: v = f*lambda"], "high"),
    ("B13b", "Unit 4", "U4AoS1", "Drawing a new standing-wave envelope at triple the frequency", ["standing waves in strings fixed at one or both ends"], "high"),
    ("B14", "Unit 4", "U4AoS1", "Labelling the E, B, c and lambda components of an EM wave diagram", ["describe light as an electromagnetic wave ... changing electric fields and associated changing magnetic fields"], "high"),
    ("B15a", "Unit 4", "U4AoS2", "Sketching a photoelectric current-voltage trace at triple intensity", ["effects of intensity of incident irradiation on the emission of photoelectrons"], "high"),
    ("B15b", "Unit 4", "U4AoS2", "Naming the stopping-voltage point on a photocurrent-voltage graph", ["kinetic energy of emitted photoelectrons: Ek max = hf - phi"], "high"),
    ("B15c", "Unit 4", "U4AoS2", "Why photocurrent falls to zero at the stopping voltage", ["kinetic energy of emitted photoelectrons: Ek max = hf - phi"], "high"),
    ("B16a", "Unit 4", "U4AoS2", "Kinetic energy of an electron from its speed", ["calculate the de Broglie wavelength of matter: lambda = h/p"], "high"),
    ("B16b", "Unit 4", "U4AoS2", "X-ray photon energy giving the same diffraction spacing as an electron beam", ["distinguish between the diffraction patterns produced by photons and electrons"], "high"),
    ("B17a", "Unit 4", "U4AoS2", "Identifying the lowest-energy spectral line in an emission spectrum", ["interpret spectra and calculate the energy of absorbed or emitted photons: delta E = hf"], "high"),
    ("B17b", "Unit 4", "U4AoS2", "Frequency of a photon emitted at a given spectral wavelength", ["interpret spectra and calculate the energy of absorbed or emitted photons: delta E = hf"], "high"),
    ("B17c", "Unit 4", "U4AoS2", "Why only certain wavelengths appear in an atomic emission spectrum", ["explain the production of atomic absorption and emission line spectra"], "high"),
    ("B18a", "Unit 3", "U3AoS2", "Effect of cable resistance on a globe's brightness in a transmission model", ["analyse the supply of power by considering transmission losses"], "high"),
    ("B18b", "Unit 4", "U4AoS3", "Identifying dependent and independent variables in a transmission-loss experiment", ["independent, dependent and controlled variables"], "high"),
    ("B18c", "Unit 3", "U3AoS2", "Deriving a cable-resistance equation from the circuit's voltage relationship", ["analyse the supply of power by considering transmission losses"], "medium"),
    ("B18d", "Unit 4", "U4AoS3", "Computing derived values to complete an experimental data table", ["methods of organising, analysing and evaluating primary data"], "high"),
    ("B18e", "Unit 4", "U4AoS3", "Plotting linearised data with uncertainty bars and a line of best fit", ["methods of organising, analysing and evaluating primary data ... sources of uncertainty and error"], "high"),
    ("B18f", "Unit 4", "U4AoS3", "Finding a circuit resistance from a graph's line of best fit", ["methods of organising, analysing and evaluating primary data"], "medium"),
]

YEAR = "2020"


def main():
    interactions = json.loads((ROOT / "public" / "interactions" / f"{YEAR}.json").read_text(encoding="utf-8-sig"))
    all_ids = {item["id"] for item in interactions}
    mapped_ids = {row[0] for row in MAPPING}

    missing = sorted(all_ids - mapped_ids)
    extra = sorted(mapped_ids - all_ids)
    if missing:
        raise SystemExit(f"Missing curriculum mapping for interaction ids: {missing}")
    if extra:
        raise SystemExit(f"Curriculum mapping references non-existent interaction ids: {extra}")

    questions = []
    for interaction_id, unit, aos, topic, skills, confidence in MAPPING:
        questions.append(
            {
                "canonicalId": f"{YEAR}-{interaction_id}",
                "interactionId": interaction_id,
                "unit": unit,
                "areaOfStudy": aos,
                "topic": topic,
                "skills": skills,
                "confidence": confidence,
                "uncertain": confidence != "high",
            }
        )

    output = {
        "studyDesignRef": "data/curriculum/study-design-2016.json",
        "paperId": YEAR,
        "generatedBy": "editorial mapping — each question's own text checked against the official 2017-2023 study design's key knowledge (see scripts/build_2020_curriculum_map.py)",
        "questions": questions,
    }

    OUT_PATH.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"Wrote {len(questions)} mapped questions to {OUT_PATH.relative_to(ROOT)}")
    by_aos = {}
    for row in MAPPING:
        by_aos[row[2]] = by_aos.get(row[2], 0) + 1
    for aos, count in sorted(by_aos.items()):
        print(f"  {aos}: {count}")
    medium_or_lower = [row[0] for row in MAPPING if row[5] != "high"]
    if medium_or_lower:
        print(f"  flagged uncertain ({len(medium_or_lower)}): {medium_or_lower}")


if __name__ == "__main__":
    main()
